	public Inventor(String name, Date birthdate, String nationality) {
		this.name = name;
		this._name = name;
		this._name_ = name;
		this.birthdate = birthdate;
		this.nationality = nationality;
		this.arrayContainer = new ArrayContainer();
		testMap = new HashMap<>();
		testMap.put("monday", "montag");
		testMap.put("tuesday", "dienstag");
		testMap.put("wednesday", "mittwoch");
		testMap.put("thursday", "donnerstag");
		testMap.put("friday", "freitag");
		testMap.put("saturday", "samstag");
		testMap.put("sunday", "sonntag");
		listOneFive.add(1);
		listOneFive.add(5);
		booleanList.add(false);
		booleanList.add(false);
		listOfNumbersUpToTen.add(1);
		listOfNumbersUpToTen.add(2);
		listOfNumbersUpToTen.add(3);
		listOfNumbersUpToTen.add(4);
		listOfNumbersUpToTen.add(5);
		listOfNumbersUpToTen.add(6);
		listOfNumbersUpToTen.add(7);
		listOfNumbersUpToTen.add(8);
		listOfNumbersUpToTen.add(9);
		listOfNumbersUpToTen.add(10);
		mapOfNumbersUpToTen.put(1,"one");
		mapOfNumbersUpToTen.put(2,"two");
		mapOfNumbersUpToTen.put(3,"three");
		mapOfNumbersUpToTen.put(4,"four");
		mapOfNumbersUpToTen.put(5,"five");
		mapOfNumbersUpToTen.put(6,"six");
		mapOfNumbersUpToTen.put(7,"seven");
		mapOfNumbersUpToTen.put(8,"eight");
		mapOfNumbersUpToTen.put(9,"nine");
		mapOfNumbersUpToTen.put(10,"ten");
	}
